namespace: tseeker
name: reconstructed
version: 1.0.0
readme: README.md
authors:
  - Emmanuel BENOÎT <tseeker@nocternity.net>
description: An inventory plug-in that can be used to generate groups programatically.
license:
  - GPL-3.0-or-later
tags: [ inventory, group, plugin ]
repository: https://github.com/tseeker/reconstructed
issues: https://github.com/tseeker/reconstructed/issues
build_ignore:
  - example/collections
  - .pytest_cache
  - .pre-commit-config.yaml
  - .yamllint
  - requirements-dev.txt
